package com.itvers.toolbox.item;

public enum UARTStatus {
    SERVICE_CONNECTED,
    SERVICE_DISCONNECTED,
    SERVICE_BINDING_DIED,
    GATT_CONNECTED,
    GATT_DISCONNECTED,
    GATT_SERVICES_DISCOVERED,
    DATA_AVAILABLE,
    DEVICE_DOES_NOT_SUPPORT_UART,
    ERROR_EMPTY_UART_SERVICE,
    ERROR_UART_SERVICE_INITIALIZATION,
    EMPTY_DEVICE,
    EMPTY_DEVICE_ADDRESS,
    ERROR_UART_SERVICE_CONNECT,
}